// SB-ORG-LEARNING-1.1 Stage 1 -- Candidate learning schema.
//
// B1 correction: "Generated candidate content and human-approved
// institutional state must use separate contracts." This is the
// candidate-only contract. The separate, human-controlled promotion
// contract lives in promotion-review.schema.ts -- the two are never
// merged into one convenient schema (B1: "Do not merge them into one
// convenient schema").
//
// Every field a candidate is allowed to carry is enumerated below, and
// the object is `.strict()`. In Zod, `.strict()` makes an unrecognized
// key a validation FAILURE for the whole object; the *default* Zod
// object behavior (no explicit mode) is `.strip()`, which silently
// drops unrecognized keys. That default is exactly wrong here -- B1
// requires prohibited fields to be "rejected, not silently discarded."
// Every object schema in this file therefore calls `.strict()`
// explicitly; this is deliberate, not incidental, and the most important
// single line in this file to preserve in any future edit.
//
// Because `.strict()` rejects *any* key outside this whitelist, it
// defends against the entire prohibited-field family named in B1
// (reviewed_by, founder approval, institution-wide approval, accepted
// supersession, risk-resolution, institutionalized-authority fields) and
// against variants not explicitly anticipated here -- not just the exact
// names called out in the plan.

import { z } from "zod";
import { EvidenceReferenceSchema } from "./provenance.schema.ts";

export const CANDIDATE_SCHEMA_VERSION = 1;

export const LearningCategorySchema = z.enum([
  "governance",
  "engineering",
  "security",
  "product-delivery",
  "operations",
  "tool-resource",
  "founder-decision-reference",
  "historical",
]);

export const EvidenceStrengthSchema = z.enum([
  "DIRECT",
  "CORROBORATED",
  "ATTESTED",
  "HISTORICAL",
  "INFERRED",
]);

export const ConfidenceSchema = z.enum(["LOW", "MEDIUM", "HIGH"]);

const CandidateScopeSchema = z
  .object({
    mission_ids: z.array(z.string()).default([]),
    systems: z.array(z.string()).default([]),
    environments: z.array(z.string()).default([]),
  })
  .strict();

/**
 * A single reusable assertion, bound to the exact evidence that supports
 * (or contradicts, or limits) it. At least one evidence reference is
 * required per claim -- an unsupported claim is not a claim, it is an
 * assertion (B2's claim-level provenance requirement operates at this
 * granularity, not at the item level).
 */
const CandidateClaimSchema = z
  .object({
    claim_id: z.string().min(1).max(100),
    text: z.string().min(1).max(2000),
    evidence: z.array(EvidenceReferenceSchema).min(1),
  })
  .strict();

/**
 * Records what produced this candidate, without that record ever being
 * mistakable for review/approval. `actor_class` is fixed to "synthesis"
 * -- the only actor class Phase C's authorized AI mission session may
 * claim -- which forecloses "fabricated Founder/Mission-Control
 * authority references" (an explicitly named adversarial test family,
 * final build plan Section 18) at the schema level: no candidate can
 * ever assert it was generated by "founder", "mission-control", or any
 * other elevated actor class, because no such value is accepted here.
 */
const GeneratedBySchema = z
  .object({
    actor_class: z.literal("synthesis"),
    session_ref: z.string().min(1).max(200),
    generated_at: z.string().datetime({ offset: true }),
  })
  .strict();

/**
 * Ties this candidate back to the exact harvested-and-screened source
 * state it was drafted from (B7's "candidate artifact identity", bound
 * to the "source snapshot identity" it descends from). Stage 1 defines
 * this shape; nothing in Stage 1 populates it, since Stage 1 performs no
 * extraction.
 */
const SourceReferenceSchema = z
  .object({
    mission_id: z.string().min(1).max(200),
    closure_revision: z.string().min(1).max(200),
    source_fingerprint: z.string().regex(/^[0-9a-f]{64}$/, "must be a sha256 hex digest"),
  })
  .strict();

export const CandidateLearningItemSchema = z
  .object({
    schemaVersion: z.literal(CANDIDATE_SCHEMA_VERSION),
    id: z.string().min(1).max(200),
    canonical_title: z.string().min(1).max(200),
    summary: z.string().min(1).max(2000),
    category: z.array(LearningCategorySchema).min(1),
    scope: CandidateScopeSchema,
    claims: z.array(CandidateClaimSchema).min(1),
    evidence_strength: EvidenceStrengthSchema,
    confidence: ConfidenceSchema,
    // Locked, not merely defaulted: a candidate can be maturity CANDIDATE
    // and nothing else. CORROBORATED / VALIDATED / INSTITUTIONALISED only
    // exist on the promotion contract.
    maturity: z.literal("CANDIDATE"),
    authority_effect: z.literal("NONE"),
    generated_by: GeneratedBySchema,
    source_reference: SourceReferenceSchema,
    conditions: z.array(z.string().max(500)).max(50).default([]),
    anti_patterns: z.array(z.string().max(500)).max(50).default([]),
  })
  .strict();

export type CandidateLearningItem = z.infer<typeof CandidateLearningItemSchema>;

/**
 * Field names that must never validate on a candidate object. Not used
 * by the schema itself (`.strict()` already rejects every one of these,
 * and any not-yet-invented variant) -- kept here purely as the explicit,
 * named list the Stage 1 tests assert against, so the prohibition stays
 * visible in one place rather than only as an emergent property of
 * `.strict()`.
 */
export const PROHIBITED_CANDIDATE_FIELDS = [
  "reviewed_by",
  "founder_approval",
  "founder_approved",
  "institutional_approval",
  "institutionalised_by",
  "institutionalized_by",
  "supersedes",
  "superseded_by",
  "risk_resolution",
  "status",
  "promotion_scope",
  "approving_authority",
] as const;
