// SB-P-1.11-GC-38R — Manual AWS4-X509 `CreateSession` signing (Lambda
// Parser EIS §7.2). No maintained pure-JS package implements the
// certificate-bound AWS4-X509 variant of SigV4 (report1.108.md §7.2's own
// finding) -- this is a small, self-contained implementation of the
// bounded, AWS-documented algorithm: identical to standard SigV4 except
// for the signing key (the caller's own private key, not a shared
// secret), the signature algorithm (asymmetric RSASSA-PKCS1-v1_5, not
// HMAC), and two added headers (`X-Amz-X509`/`X-Amz-X509-Chain`).
//
// Server-only. Never imported by client-bundled code. The private key is
// imported non-extractable wherever the runtime allows it, held only in
// memory for the single CreateSession call that needs it, and never
// logged, returned, or persisted.
//
// This module intentionally targets RSA end-entity certificates
// (AWS4-X509-RSA-SHA256) -- the key type generated by the parser
// deployment workflow -- not the ECDSA variant.

const ROLES_ANYWHERE_SERVICE = "rolesanywhere";
const ALGORITHM = "AWS4-X509-RSA-SHA256";

export interface RolesAnywhereSessionCredentials {
  accessKeyId: string;
  secretAccessKey: string;
  sessionToken: string;
  expiration: string;
}

export interface CreateSessionParams {
  region: string;
  trustAnchorArn: string;
  profileArn: string;
  roleArn: string;
  durationSeconds: number;
  /** PEM-encoded end-entity certificate. */
  certificatePem: string;
  /** PEM-encoded intermediate chain, if any (may be empty). */
  certificateChainPem: string;
  /** PKCS8 PEM-encoded RSA private key for the end-entity certificate. */
  privateKeyPem: string;
}

// ---------------------------------------------------------------------------
// PEM / DER helpers.
// ---------------------------------------------------------------------------

function pemToDer(pem: string): Uint8Array {
  const base64 = pem
    .replace(/-----BEGIN [^-]+-----/g, "")
    .replace(/-----END [^-]+-----/g, "")
    .replace(/\s+/g, "");
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function toBase64(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Minimal DER/ASN.1 walker sufficient to read a length-prefixed TLV element
 * starting at `offset`. Handles short and long-form lengths (DER, not the
 * full BER grammar) -- sufficient for the well-formed X.509v3 certificates
 * this system generates and consumes itself.
 */
function readTlv(
  der: Uint8Array,
  offset: number,
): { tag: number; contentStart: number; contentEnd: number; next: number } {
  const tag = der[offset];
  const lengthByte = der[offset + 1];
  let contentStart: number;
  let length: number;
  if ((lengthByte & 0x80) === 0) {
    length = lengthByte;
    contentStart = offset + 2;
  } else {
    const numLengthBytes = lengthByte & 0x7f;
    length = 0;
    for (let i = 0; i < numLengthBytes; i++) {
      length = (length << 8) | der[offset + 2 + i];
    }
    contentStart = offset + 2 + numLengthBytes;
  }
  const contentEnd = contentStart + length;
  return { tag, contentStart, contentEnd, next: contentEnd };
}

/**
 * Converts an unsigned big-endian byte sequence to its decimal string
 * representation, with no precision loss (BigInt, not Number).
 */
function bytesToDecimal(bytes: Uint8Array): string {
  let value = 0n;
  for (const byte of bytes) value = value * 256n + BigInt(byte);
  return value.toString(10);
}

/**
 * Extracts the certificate serial number (the value AWS4-X509 places in the
 * Authorization header's Credential field in place of an access key id) as
 * a decimal string, from a DER-encoded X.509 certificate. AWS IAM Roles
 * Anywhere's CreateSession signing process requires the decimal
 * representation of the certificate serial number at this exact position
 * (report1.172.md's Phase A review; instruction1.174.md) -- not hexadecimal.
 *
 * Certificate ::= SEQUENCE { tbsCertificate, signatureAlgorithm, signatureValue }
 * TBSCertificate ::= SEQUENCE { [0] version (optional, context tag 0xA0),
 *                                serialNumber INTEGER, ... }
 */
export function extractSerialNumberDecimal(der: Uint8Array): string {
  const certificate = readTlv(der, 0);
  if (certificate.tag !== 0x30) throw new Error("PARSER_INGRESS_CERT_NOT_SEQUENCE");
  const tbsCertificate = readTlv(der, certificate.contentStart);
  if (tbsCertificate.tag !== 0x30) throw new Error("PARSER_INGRESS_CERT_TBS_NOT_SEQUENCE");

  let cursor = tbsCertificate.contentStart;
  const first = readTlv(der, cursor);
  if (first.tag === 0xa0) {
    // Explicit [0] version tag present; skip it.
    cursor = first.next;
  }
  const serialNumber = readTlv(der, cursor);
  if (serialNumber.tag !== 0x02) throw new Error("PARSER_INGRESS_CERT_SERIAL_NOT_INTEGER");
  let bytes = der.subarray(serialNumber.contentStart, serialNumber.contentEnd);
  // DER INTEGER encoding: a single leading 0x00 byte only present to keep
  // the value non-negative is not part of the logical serial number value.
  if (bytes.length > 1 && bytes[0] === 0x00 && (bytes[1] & 0x80) !== 0) {
    bytes = bytes.subarray(1);
  }
  return bytesToDecimal(bytes);
}

// ---------------------------------------------------------------------------
// SigV4-family canonical request / string-to-sign construction (identical
// shape to standard SigV4; report1.108.md §7.2).
// ---------------------------------------------------------------------------

async function sha256Hex(data: Uint8Array | string): Promise<string> {
  const bytes = typeof data === "string" ? new TextEncoder().encode(data) : data;
  const digest = await crypto.subtle.digest("SHA-256", bytes.slice().buffer as ArrayBuffer);
  return toHex(new Uint8Array(digest));
}

function amzDateStamp(date: Date): { amzDate: string; dateStamp: string } {
  const iso = date.toISOString().replace(/[:-]|\.\d{3}/g, "");
  const amzDate = iso; // YYYYMMDDTHHMMSSZ
  const dateStamp = amzDate.slice(0, 8); // YYYYMMDD
  return { amzDate, dateStamp };
}

interface CanonicalRequestResult {
  canonicalRequest: string;
  signedHeaders: string;
  headers: Record<string, string>;
}

function buildCanonicalRequest(
  method: string,
  uri: string,
  headers: Record<string, string>,
  hashedPayload: string,
): CanonicalRequestResult {
  const sortedHeaderNames = Object.keys(headers)
    .map((h) => h.toLowerCase())
    .sort();
  const canonicalHeaders = sortedHeaderNames
    .map((name) => `${name}:${headers[name].trim()}\n`)
    .join("");
  const signedHeaders = sortedHeaderNames.join(";");
  const canonicalRequest = [
    method,
    uri,
    "", // no query string
    canonicalHeaders,
    signedHeaders,
    hashedPayload,
  ].join("\n");
  return { canonicalRequest, signedHeaders, headers };
}

// ---------------------------------------------------------------------------
// CreateSession.
// ---------------------------------------------------------------------------

/**
 * Signs and sends one AWS IAM Roles Anywhere `CreateSession` request using
 * the exact end-entity certificate/private key supplied. The private key
 * is imported for this single operation and never persisted or returned.
 */
export async function createRolesAnywhereSession(
  params: CreateSessionParams,
): Promise<RolesAnywhereSessionCredentials> {
  const host = `rolesanywhere.${params.region}.amazonaws.com`;
  const uri = "/sessions";
  const url = `https://${host}${uri}`;

  const body = JSON.stringify({
    durationSeconds: params.durationSeconds,
    profileArn: params.profileArn,
    roleArn: params.roleArn,
    trustAnchorArn: params.trustAnchorArn,
  });

  // instruction1.172.md / instruction1.186.md -- sanitized failure
  // categorization for the Roles Anywhere credential path. Every catch here
  // discards the original error entirely and throws a fixed, non-secret
  // category string only -- never certificate/key content, never a
  // provider body, never anything derived from the caught error itself.
  // The caller (parser-lease.ts) no longer extracts/logs these category
  // strings post-C5 (instruction1.186.md's repository cleanup removed that
  // consumer deliberately, conservatively, without touching this validated
  // signing implementation) -- they remain here only as an inert,
  // already-sanitized fail-closed boundary around each risky step.
  let certDer: Uint8Array;
  let chainDer: Uint8Array | null;
  let serialDecimal: string;
  try {
    certDer = pemToDer(params.certificatePem);
    chainDer =
      params.certificateChainPem.trim().length > 0 ? pemToDer(params.certificateChainPem) : null;
    serialDecimal = extractSerialNumberDecimal(certDer);
  } catch {
    throw new Error("certificate_parse_failed");
  }

  const now = new Date();
  const { amzDate, dateStamp } = amzDateStamp(now);
  const hashedPayload = await sha256Hex(body);

  const headers: Record<string, string> = {
    host,
    "x-amz-date": amzDate,
    "x-amz-x509": toBase64(certDer),
    "content-type": "application/json",
  };
  if (chainDer) headers["x-amz-x509-chain"] = toBase64(chainDer);

  const { canonicalRequest, signedHeaders } = buildCanonicalRequest(
    "POST",
    uri,
    headers,
    hashedPayload,
  );
  const hashedCanonicalRequest = await sha256Hex(canonicalRequest);
  const credentialScope = `${dateStamp}/${params.region}/${ROLES_ANYWHERE_SERVICE}/aws4_request`;
  const stringToSign = [ALGORITHM, amzDate, credentialScope, hashedCanonicalRequest].join("\n");

  let privateKey: CryptoKey;
  try {
    privateKey = await crypto.subtle.importKey(
      "pkcs8",
      pemToDer(params.privateKeyPem).slice().buffer as ArrayBuffer,
      { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
      false, // non-extractable
      ["sign"],
    );
  } catch {
    throw new Error("private_key_import_failed");
  }

  let signatureHex: string;
  try {
    const signatureBytes = new Uint8Array(
      await crypto.subtle.sign(
        "RSASSA-PKCS1-v1_5",
        privateKey,
        new TextEncoder().encode(stringToSign).slice().buffer as ArrayBuffer,
      ),
    );
    signatureHex = toHex(signatureBytes);
  } catch {
    throw new Error("signature_failed");
  }

  const authorizationHeader = `${ALGORITHM} Credential=${serialDecimal}/${credentialScope}, SignedHeaders=${signedHeaders}, Signature=${signatureHex}`;

  let response: Response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: { ...headers, authorization: authorizationHeader },
      body,
    });
  } catch {
    throw new Error("create_session_network_failed");
  }

  if (!response.ok) {
    // Never surface the raw provider body -- it may echo request detail.
    throw new Error(`create_session_http_failed:${response.status}`);
  }

  let payload: {
    credentialSet?: {
      credentials?: {
        accessKeyId: string;
        secretAccessKey: string;
        sessionToken: string;
        expiration: string;
      };
    }[];
  };
  try {
    payload = await response.json();
  } catch {
    throw new Error("create_session_malformed_response");
  }
  const credentials = payload.credentialSet?.[0]?.credentials;
  if (!credentials) {
    throw new Error("create_session_malformed_response");
  }
  return credentials;
}
