-- SB-OPS-PROD-SYNC-1.0 instruction1.6 Phase B -- schema-level one-to-one
-- guarantee that an Inventory item is the dedicated identity of at most
-- one Catalog product per business.
--
-- ============================================================================
-- DO NOT APPLY TO PRODUCTION YET.
--
-- Production (gysgzasfcjvtrgaigfyn) is independently confirmed to
-- currently contain a duplicate: active products `Milma Milk` and
-- `Mango` both reference Inventory item `AVT Tea Powder`
-- (report1.5.md/report1.6.md). Applying this constraint against that
-- state will fail outright -- CREATE UNIQUE INDEX / ADD CONSTRAINT
-- UNIQUE against non-unique data is rejected by Postgres itself, not by
-- any guard added here. That failure is the intended, mechanical safety
-- property of this file: it cannot silently succeed while the duplicate
-- exists.
--
-- Deployment order: this file has no dependency on the Phase A
-- migration (20260902120000_..._phase_a_link_reuse_guard.sql), which is
-- independently safe to deploy on its own at any time. This file
-- specifically requires, first, the Phase C repair (report1.6.md) to be
-- designed, separately authorized, and executed against production so
-- `Mango`/`Milma Milk`/`AVT Tea Powder` no longer collide -- and only
-- then may this file's own execution be separately authorized per
-- docs/migration/README.md's Default-Deny Execution Rule. Authoring and
-- isolated-test-project verification of this file (report1.6.md) create
-- no such authorization by themselves. See docs/migration/README.md for
-- this file's tracked status.
-- ============================================================================
--
-- Lifecycle predicate (instruction1.6 Phase B explicitly asks this to be
-- determined, not assumed): this constraint is NOT filtered by
-- catalog_products.status. An archived product's inventory_item_id
-- remains permanently reserved, exactly like this same table's existing
-- name/SKU/barcode uniqueness constraints, whose own schema comment
-- already states the policy this migration extends for consistency:
-- "Archived identities remain reserved: plain, non-partial constraints"
-- (20260806120000_sb_p_1_11_impl_1_stage1_schema.sql). Reactivating an
-- archived product requires no special handling under this rule: since
-- archive/reactivate (archive_catalog_product, reactivate_catalog_product)
-- never touch inventory_item_id, a reactivated product's link was never
-- released and this constraint was never at risk of being violated by
-- it. A plain (non-partial) UNIQUE constraint is sufficient here, exactly
-- as for the sibling identity columns: Postgres treats each NULL
-- inventory_item_id (a non-stock-tracked product) as distinct from every
-- other NULL, so multiple non-stock-tracked products remain unaffected.
--
-- This constraint is intentionally the sole authoritative guarantee;
-- the Phase A application-level guard uses the identical predicate
-- (business_id, inventory_item_id, excluding the row's own id) so
-- neither layer can accept a case the other would reject.

ALTER TABLE public.catalog_products
  ADD CONSTRAINT catalog_products_business_inventory_item_uniq
  UNIQUE (business_id, inventory_item_id);
